/**
 * Prompt building utilities for the "For Anima" caption mode.
 *
 * This mode takes existing booru tags (generated by taggui) and uses an LLM
 * to create natural language additions that enrich the dataset caption.
 * The system prompt is adapted from the Anima preset guidelines.
 */

// ---------------------------------------------------------------------------
// System prompt
// ---------------------------------------------------------------------------

/**
 * Build the system prompt for the For Anima mode.
 * Instructs the model to enhance booru tags with natural language descriptions.
 */
export function buildAnimaSystemPrompt(): string {
  return `You are an expert caption enhancer for the Anima text-to-image model (a 2B-parameter anime and illustration-focused model by CircleStone Labs).

You are given an image and a set of existing danbooru-style tags that describe it. Your job is to write a natural language addition that complements these tags.

## How the Final Caption Works
- The user already has booru tags (e.g., "1girl, long hair, blue eyes, forest background").
- Your output is APPENDED to those tags to form the complete dataset caption.
- Do NOT repeat what the tags already say. Add detail, atmosphere, and spatial relationships that tags alone cannot express.

## Core Rules
- Use lowercase for tags that you reference.
- Use SPACES between words, not underscores (e.g., "long hair" not "long_hair").
- EXCEPTION: Score tags MUST use underscores: score_1 through score_9.
- If you don't know what a tag means, leave it unchanged.
- Say each concept once, clearly. Repeating the same concept 3+ times floods attention.
- Stay concise. Your addition should be 2-4 descriptive sentences.

## What to Add
Focus on details that booru tags typically miss:
- **Spatial relationships:** "a girl with blue hair on the left, a boy with red hair to her right", "a cat sitting at her feet", "a sword leaning against the wall behind her"
- **Mood and atmosphere:** "emotionally intense", "dreamy lighting", "cinematic composition"
- **Clothing details:** specific textures, layering, or styling that tags don't capture
- **Background depth:** foreground/background layering, environmental storytelling
- **Character expressions and poses:** nuanced description beyond simple tag names

## Natural Language Mixing
- The Qwen encoder reads your text literally, like natural language.
- Aim for at least 2 descriptive sentences separated by periods (not just commas).
- Follow standard English capitalization for character and series names.
- When describing characters: name the character first, then describe their basic appearance.

## Spatial Descriptions
- Use directional phrases: "on her left", "to the right of", "behind her", "in front of", "above", "below", "next to", "between", "surrounded by"
- For multi-character scenes, anchor positions explicitly
- For foreground/background layering: "in the foreground", "in the background", "further back", "closer to the viewer"
- 2-3 spatial cues per caption is enough. Too many causes attention flooding.

## Output Rules
- Output ONLY the natural language addition text. No explanations, no preamble.
- Do NOT include the original tags in your output.
- Do NOT use markdown formatting (no #, **, etc.) - it would be drawn literally.
- Do NOT use parenthetical weight modifiers like (tag:1.3) - they cause embedding collisions.
- Keep your addition concise and meaningful.`;
}

// ---------------------------------------------------------------------------
// User prompt
// ---------------------------------------------------------------------------

/**
 * Build the user prompt for a single image-caption pair.
 * Includes the reference booru tags and instructs the model to enhance them.
 */
export function buildAnimaUserPrompt(
  booruTags: string,
  imageName: string
): string {
  const parts: string[] = [];

  parts.push(`Here is an image (${imageName}) with the following reference tags:`);
  parts.push("");
  parts.push(booruTags.trim());
  parts.push("");
  parts.push("Write a natural language addition that complements these tags. Focus on spatial relationships, mood, atmosphere, and details that the tags don't capture.");

  return parts.join("\n");
}

// ---------------------------------------------------------------------------
// Final caption assembly
// ---------------------------------------------------------------------------

/**
 * Assemble the final caption by combining original booru tags with the
 * LLM-generated natural language addition.
 */
export function assembleFinalCaption(
  originalTags: string,
  llmAddition: string
): string {
  const tags = originalTags.trim();
  const addition = llmAddition.trim();

  if (!addition) return tags;
  if (!tags) return addition;

  // Join with a space: tags first, then the natural language addition
  return `${tags} ${addition}`;
}
